      SUBROUTINE COMPLETE
      INTEGER I,J,K
      DOUBLE PRECISION U
c      INCLUDE 'model.txt'
c      INCLUDE 'conpar.txt'
c      INCLUDE 'setcon.txt'
c      INCLUDE 'series.txt'
c      INCLUDE 'veccom.txt'
c      INCLUDE 'redcom.txt'
c      INCLUDE 'seacom.txt'
c      INCLUDE 'repar3.txt'
C*****model.txt
      INTEGER PFI,ARP,VRI,CCV,LYAP,SCC,fct
      DOUBLE PRECISION SCALE,VR,CONST,PHI(20),PRDG
      COMMON/MODEL/SCALE,VR,CONST,PHI,PRDG,PFI,ARP,VRI,CCV,LYAP,SCC,fct
      integer for, fty
      common/model/for, fty
C*****conpar.txt    
      INTEGER NIT,OPM,RGM,KUP,KSP,KST
      DOUBLE PRECISION REQ,CONCRIT,RPERT,IVLAM,FAC,STLAM,SMLAM,GTLAM
c      COMMON/CONPAR/NIT,OPM,RGM,REQ,CONCRIT,RPERT,IVLAM,FAC,STLAM,
c     * SMLAM,GTLAM,KUP,KSP,KST
      COMMON/CONPAR/REQ,CONCRIT,RPERT,IVLAM,FAC,STLAM,
     * SMLAM,GTLAM,NIT,OPM,RGM,KUP,KSP,KST

C*****setcon.txt
      LOGICAL CONV,FAIL
      INTEGER NP,ITCT,PPIND
      DOUBLE PRECISION CSO,CSZ,LAM,SSOLD,GMOLD,GMNEW,SIGSQ,OLDB(22)
c      COMMON/SETCON/CONV,FAIL,NP,ITCT,PPIND,CSO,CSZ,LAM,SSOLD,
c     *GMOLD,GMNEW,SIGSQ,OLDB
      COMMON/SETCON/CSO,CSZ,LAM,SSOLD,
     *GMOLD,GMNEW,SIGSQ,OLDB,CONV,FAIL,NP,ITCT,PPIND
C*****series.txt
      CHARACTER*40 NAME
      INTEGER LEN
      DOUBLE PRECISION TIM(500),SER(500),TDIF(500)
c      COMMON/SERIES/NAME,LEN,TIM,SER,TDIF
      COMMON/SERIES/TIM,SER,TDIF,NAME,LEN
C*****veccom.txt
      DOUBLE PRECISION B(22),NEWB(22),PERB(22),DELB(22),
     * ERR(500),RES(500),PRES(22,500),sres(500)
      COMMON/VECCOM/B,NEWB,PERB,DELB,ERR,RES,PRES,sres
C*****redcom.txt
      DOUBLE PRECISION GRAD(22),SSP(22,22)
      COMMON/REDCOM/GRAD,SSP
C*****seacom.txt
      LOGICAL SOLV
      DOUBLE PRECISION ESSP(22,22),ECOV(22,22)
c      COMMON/SEACOM/SOLV,ESSP,ECOV
      COMMON/SEACOM/ESSP,ECOV,SOLV

C*****repar3.txt
      DOUBLE PRECISION ALPHA(21),ROOTR(20),ROOTI(20),XVECR(20),
     *XVECI(20)
      COMMON/REPAR3/ALPHA,ROOTR,ROOTI,XVECR,XVECI

      CALL NEWLINE
      PRINT *,'PROCESSING COMPLETED'
      IF(ITCT.GE.NIT)THEN
        I=NIT
      ELSE
        I=ITCT
      END IF
      PRINT *,I,' ITERATIONS COMPLETED'
      IF(CONV)THEN
        PRINT *,'CONVERGENCE ACHIEVED'
      ELSE
        PRINT *,'CONVERGENCE NOT ACHIEVED'
      END IF
      IF(FAIL)THEN
        PRINT *,'SEARCH FAILED TO PROGRESS'
      ELSE
        PRINT *,'SEARCH PROGRESSED'
      END IF
      DO 100 I=1,NP
      DELB(I)=0.0D0
      DO 100 J=1,NP
      ESSP(I,J)=SSP(I,J)
  100 CONTINUE
      CALL SIMI
      K=LEN-ARP
      IF(VRI.EQ.1)K=K-1
      IF(CCV.EQ.2)K=K-1
      U=SSOLD/K
      SIGSQ=U/GMOLD
      DO 101 I=1,NP
      DO 101 J=1,NP
      ESSP(I,J)=ESSP(I,J)*U  
  101 CONTINUE
c added by Z.W.
c      OPEN(UNIT=4,FILE='cov.dat',STATUS='NEW')
      OPEN(UNIT=4,FILE='cov.dat',STATUS='unknown')
      write(4,95) ((ESSP(I,J),J=1,NP-1),I=1,NP-1)
   95 FORMAT(5E16.8)
c Note: NP-th parameter is the constant estimator in the last line
      close(unit=4)
c end by Z.W.   
      DO 102 I=1,NP
      DELB(I)=DSQRT(ESSP(I,I))
  102 CONTINUE
      DO 103 I=1,NP
      U=DELB(I)
      DO 103 J=1,NP
      ESSP(I,J)=ESSP(I,J)/(U*DELB(J))
  103 CONTINUE
      CALL NEWLINE
      PRINT *,'FINAL SUM OF SQUARES: ',SSOLD
      PRINT *,'MEAN SUM OF SQUARES : ',SIGSQ*GMOLD
      PRINT *,'INNOVATION PROCESS VARIANCE ESTIMATE: ',SIGSQ
      PRINT *,'GEOMETRIC MEAN VARIANCE MULTIPLIER:   ',GMOLD
      PRINT *,'FINAL PARAMETER VALUES:'
      DO 104 I=1,NP
      B(I)=OLDB(I)
      PRINT *,'   ',I,'  ',B(I),'   +/- ',DELB(I)
  104 CONTINUE
      CALL NEWLINE
      PRINT *,'CORRELATION MATRIX:'
      DO 106 I=1,NP
      WRITE(6,105)(ESSP(I,J),J=1,I)
  105 FORMAT(1H ,7(D10.3,2X))
  106 CONTINUE
c      OPEN(UNIT=4,FILE='parest.dat',STATUS='NEW')
      open(unit=4,file='parest.dat',status='unknown')
      WRITE(4,195)
  195 FORMAT('MOD.PAR.IND., ORDER, NO.PAR., VAR.RAT.IND., CON.IND.')
      WRITE(4,196) PFI,ARP,NP,VRI,CCV
  196 FORMAT(5I10)
      WRITE(4,197)
  197 FORMAT('SCALE , INNOVATION VARIANCE')
      WRITE(4,198) SCALE,SIGSQ
  198 FORMAT(5E16.8)
      WRITE(4,199)
  199 FORMAT('PARAMETERS')
      WRITE(4,198) (B(I),I=1,NP)
      WRITE(4,200)
  200 FORMAT('STANDARD ERRORS')
      WRITE(4,198) (DELB(I),I=1,NP)
      WRITE(4,201)
  201 FORMAT('CORRELATIONS')
      WRITE(4,198) ((ESSP(I,J),J=1,I),I=1,NP)
      WRITE(4,202)
      CALL ROOTS
  202 FORMAT('ROOTS:REAL PARTS THEN IMAGINARY')
      WRITE(4,198) (ROOTR(I),I=1,ARP)
      WRITE(4,198) (ROOTI(I),I=1,ARP)
      CLOSE(UNIT=4)
c added by Z.W.
c     the last element of phi.dat is the estimate of the mean
c      OPEN(UNIT=4,FILE='phi.dat',STATUS='NEW')
      OPEN(UNIT=4,FILE='phi.dat',STATUS='unknown')
      WRITE(4,300) (B(I),I=1,NP)
  300 FORMAT(5E16.8)
      CLOSE(UNIT=4)
c end by Z.W.
      RETURN
      END
