      SUBROUTINE SETUPDATE (PHI1)
      INTEGER I,ARP
c      INCLUDE 'setcon.txt'
C*****setcon.txt
      LOGICAL CONV,FAIL
      INTEGER NP,ITCT,PPIND
      DOUBLE PRECISION CSO,CSZ,LAM,SSOLD,GMOLD,GMNEW,SIGSQ,OLDB(22)
c      COMMON/SETCON/CONV,FAIL,NP,ITCT,PPIND,CSO,CSZ,LAM,SSOLD,
c     *GMOLD,GMNEW,SIGSQ,OLDB
      COMMON/SETCON/CSO,CSZ,LAM,SSOLD,
     *GMOLD,GMNEW,SIGSQ,OLDB,CONV,FAIL,NP,ITCT,PPIND

      DOUBLE PRECISION PHI(20)
      COMMON/MODEL/PHI,ARP
      DOUBLE PRECISION PHI1(20)

      DO 100 I=1, ARP+1
         PHI1(I)=PHI(I)
 100  CONTINUE
      RETURN
      END
